name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
    inputs:
      ref:
        description: The branch, tag or SHA to checkout
        default: main
        type: string
  schedule:
    # Deploy hourly between 9am and 7pm on weekdays
    - cron: "0 9-19 * * 1-5"

jobs:
  test-ruby:
    name: Test Ruby
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref || github.ref }}
          show-progress: false
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - run: bundle exec rake
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SKIP_PROXY_PAGES: true
