name: Deploy to development

on:
  push:
    branches-ignore:
      - main
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

env:
  AWS_REGION: 'eu-west-2'
  IAM_ROLE_ARN: 'arn:aws:iam::844815912454:role/GithubActions-Tech-Docs-Role'

jobs:
  test:
    if: ${{ github.event_name == 'workflow_dispatch' || github.event_name == 'push' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - run: bundle exec rake
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SKIP_PROXY_PAGES: true
  build-dev:
    needs: test
    uses: ./.github/workflows/build.yml

  deploy:
    runs-on: ubuntu-latest
    needs:
      - test
      - build-dev

    steps:
      - uses: actions/download-artifact@v4
        if: ${{ success() }}
        with:
          name: build-artifact
          path: build/

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.IAM_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Upload to S3
        run: |
          ACCOUNT_ID=$(aws sts get-caller-identity --query 'Account' --output text)
          aws s3 cp --recursive build/ s3://trade-tariff-tech-docs-${ACCOUNT_ID}/
